// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZdI26jHpeOOZH_xzAHrGSYkscK2Jyj1Y',
    appId: '1:5443914367:web:3eb51c244107cca6a7cd4a',
    messagingSenderId: '5443914367',
    projectId: 'ahabit-65d7f',
    authDomain: 'ahabit-65d7f.firebaseapp.com',
    storageBucket: 'ahabit-65d7f.firebasestorage.app',
    measurementId: 'G-YBMYVT45ZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZcy3EIFhkfC_vAWN61HqZ41FWiDC1b-0',
    appId: '1:5443914367:android:c456f916e3bd2cdca7cd4a',
    messagingSenderId: '5443914367',
    projectId: 'ahabit-65d7f',
    storageBucket: 'ahabit-65d7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbD1YFNXC0k1y__n9plE4_6gWJM36-Yz0',
    appId: '1:5443914367:ios:686b7c25a418b56fa7cd4a',
    messagingSenderId: '5443914367',
    projectId: 'ahabit-65d7f',
    storageBucket: 'ahabit-65d7f.firebasestorage.app',
    iosBundleId: 'com.example.habitPunch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbD1YFNXC0k1y__n9plE4_6gWJM36-Yz0',
    appId: '1:5443914367:ios:686b7c25a418b56fa7cd4a',
    messagingSenderId: '5443914367',
    projectId: 'ahabit-65d7f',
    storageBucket: 'ahabit-65d7f.firebasestorage.app',
    iosBundleId: 'com.example.habitPunch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZdI26jHpeOOZH_xzAHrGSYkscK2Jyj1Y',
    appId: '1:5443914367:web:c95727e2110af90da7cd4a',
    messagingSenderId: '5443914367',
    projectId: 'ahabit-65d7f',
    authDomain: 'ahabit-65d7f.firebaseapp.com',
    storageBucket: 'ahabit-65d7f.firebasestorage.app',
    measurementId: 'G-88R7LY7KS6',
  );
}
